package com.example.backend.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity  // Specifies that this class is a JPA entity and will be mapped to a database table
public class Book {

    @Id  // Marks this field as the primary key of the entity
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Specifies that the ID value will be auto-generated by the database
    private Long id;

    private String title;  // This field will store the title of the book

    // Getter for id field
    public Long getId() {
        return id;
    }

    // Setter for id field
    public void setId(Long id) {
        this.id = id;
    }

    // Getter for title field
    public String getTitle() {
        return title;
    }

    // Setter for title field
    public void setTitle(String title) {
        this.title = title;
    }
}
